#!/usr/bin/env node
/* Builds the engine inside skills/rupeecheck-content/ from the site's own files, so the content skill always computes with the live site's code.
   Run:  node scripts/build-skill.js          (copy the calculation modules, extract each page's default inputs, stamp ENGINE.json)
         node scripts/build-skill.js --check  (exit 1 if the committed engine differs from the site: used by the tests and CI)
   Re-run after ANY change to a calculator, a tax rule, an exchange-rate default or a page default, then re-package the skill. */
'use strict';
const fs = require('fs'), path = require('path'), crypto = require('crypto'), { execSync } = require('child_process');
const ROOT = path.join(__dirname, '..'), SKILL = path.join(ROOT, 'skills', 'rupeecheck-content'), ENGINE = path.join(SKILL, 'engine');
const MODULES = ['tax', 'invest', 'loan', 'deposit', 'hra', 'gratuity', 'fire', 'rentbuy', 'abroad', 'returning', 'swp'];
const PAGES = ['sip-calculator', 'emi-calculator', 'fd-calculator', 'gratuity-calculator', 'hra-calculator', 'fire-calculator', 'rent-vs-buy-calculator', 'return-calculator', 'abroad-calculator', 'swp-calculator'];
const TAX_YEAR = '2026-27', FX_DEFAULTS_DATE = '2026-10-02';        // update FX_DEFAULTS_DATE whenever the exchange-rate defaults in assets/abroad.js are refreshed
const sha = buf => crypto.createHash('sha256').update(buf).digest('hex').slice(0, 16);

function pageDefaults(file) {                                       // the value each input has when the page first opens
  const h = fs.readFileSync(path.join(ROOT, file + '.html'), 'utf8'), d = {};
  for (const m of h.matchAll(/<input\b([^>]*)>/g)) { const a = m[1], id = (a.match(/\bid="([^"]+)"/) || [])[1]; if (!id) continue;
    if (/type="checkbox"/.test(a)) d[id] = /\bchecked\b/.test(a); else { const v = (a.match(/\bvalue="([^"]*)"/) || [])[1]; if (v !== undefined) d[id] = v; } }
  for (const m of h.matchAll(/<select\b[^>]*\bid="([^"]+)"[^>]*>([\s\S]*?)<\/select>/g)) { const opts = [...m[2].matchAll(/<option\b([^>]*)>/g)].map(o => ({ v: (o[1].match(/value="([^"]*)"/) || [])[1], sel: /\bselected\b/.test(o[1]) })); const s = opts.find(o => o.sel) || opts[0]; if (s) d[m[1]] = s.v; }
  for (const m of h.matchAll(/<div class="seg" id="([^"]+)"[^>]*>([\s\S]*?)<\/div>/g)) { const on = [...m[2].matchAll(/<button\b([^>]*)>/g)].find(b => /class="on"/.test(b[1])); if (on) d[m[1]] = (on[1].match(/data-v="([^"]*)"/) || [])[1]; }
  return d;
}

function build() {
  const files = {};
  for (const m of MODULES) { const buf = fs.readFileSync(path.join(ROOT, 'assets', m + '.js')); files[m + '.js'] = { buf, sha: sha(buf) }; }
  const defaults = {}; for (const p of PAGES) defaults[p] = pageDefaults(p);
  let commit = ''; try { commit = execSync('git rev-parse --short HEAD', { cwd: ROOT, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); } catch (e) {}
  const meta = { note: 'Generated by scripts/build-skill.js from the site. Do not edit by hand.', builtOn: new Date().toISOString().slice(0, 10), sourceCommit: commit, taxYear: TAX_YEAR, fxDefaultsDate: FX_DEFAULTS_DATE, files: Object.fromEntries(Object.entries(files).map(([k, v]) => [k, v.sha])) };
  return { files, defaults: JSON.stringify(defaults, null, 1) + '\n', meta };
}

const arg = process.argv[2], b = build();
if (arg === '--check') {
  let bad = [];
  for (const [name, { buf }] of Object.entries(b.files)) { const p = path.join(ENGINE, name); if (!fs.existsSync(p) || sha(fs.readFileSync(p)) !== sha(buf)) bad.push(name); }
  const dp = path.join(ENGINE, 'page-defaults.json'); if (!fs.existsSync(dp) || fs.readFileSync(dp, 'utf8') !== b.defaults) bad.push('page-defaults.json');
  if (bad.length) { console.error('The skill engine is out of date with the site: ' + bad.join(', ') + '\nRun: node scripts/build-skill.js'); process.exit(1); }
  console.log('Skill engine matches the site.'); process.exit(0);
}
fs.mkdirSync(ENGINE, { recursive: true });
for (const [name, { buf }] of Object.entries(b.files)) fs.writeFileSync(path.join(ENGINE, name), buf);
fs.writeFileSync(path.join(ENGINE, 'page-defaults.json'), b.defaults);
fs.writeFileSync(path.join(ENGINE, 'ENGINE.json'), JSON.stringify(b.meta, null, 2) + '\n');
console.log('Skill engine built: ' + Object.keys(b.files).length + ' modules, defaults for ' + PAGES.length + ' pages, tax year ' + TAX_YEAR + '.');
